apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      app: jenkins-app
  replicas: 1
  template:
    metadata:  # Corrected typo from 'metadate' to 'metadata'
      labels:
        app: jenkins-app
    spec:
      containers:
        - name: jenkins-app
          image: daudidrees/myimage:latest
          ports:
            - containerPort: 8080

