apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins-app
  ports:
    - protocol: TCP  # Corrected typo from 'protocal' to 'protocol'
      port: 8080
      targetPort: 8080
  type: NodePort
